---

- name: Checking if the Consul service exists
  stat:
    path: /etc/systemd/system/consul.service
  register: consul_service

- name: Creating Consul service from template
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: "0644"
  when: not consul_service.stat.exists

- name: Reloading the systemd daemon
  systemd:
    daemon_reload: yes
  when: not consul_service.stat.exists