---

- name: Checking for existing encryption values in config.json
  shell: grep -Po '\"encrypt\"[:]\s\K\"(.*)\"' /etc/consul.d/config.json | tr -d '"'
  register: consul_encrypt_grep
  delegate_to: "{{ groups['webservers'][0] }}"
  run_once: true

- name: Generating new encryption key
  shell: /usr/local/bin/consul keygen
  register: consul_encrypt
  delegate_to: "{{ groups['webservers'][0] }}"
  run_once: true
  when: consul_encrypt_grep.stdout | length == 0

- name: Defining variable for encryption key
  set_fact:
   consul_encrypt: "{{ consul_encrypt.stdout }}"
  run_once: true
  when: consul_encrypt_grep.stdout | length == 0

- name: Setting existing value as encryption variable
  set_fact:
   consul_encrypt: "{{ consul_encrypt_grep.stdout }}"
  when: consul_encrypt_grep.stdout | length > 0

### For debug purposes
#- name: Defined encryption key
#  debug:
#    var: consul_encrypt