---
- file:
    path: /usr/local/bin/consul
    state: directory
    mode: 0755

- unarchive:
    src: https://releases.hashicorp.com/consul/1.7.2/consul_1.7.2_linux_amd64.zip
    dest: /usr/local/bin/consul
    remote_src: yes

- stat:
    path: '{{ consul_scripts }}'
  register: scripts_dir

- file:
    path: '{{ consul_scripts }}'
    state: directory
    mode: 0755
  when: not scripts_dir.stat.exists

- stat:
    path: '{{ consul_data }}'
  register: var_dir

- file:
    path: '{{ consul_data }}'
    state: directory
    mode: 0755
  when: not var_dir.stat.exists