---
- name: Host - Install consul and create directories
  - import_tasks: install_consul.yml
  tags:
  - install

- name: Consul - Generate secret
  import_tasks: generate_key.yml
  tags:
  - keygen
  - config

- name: Consul - Generate config
  import_tasks: generate_config.yml
  tags:
  - config

- name: Consul - Create service
  import_tasks: create_service.yml
  rescue:
  tags:
  - service

- name: Consul - Start and verify running instances.
  import_tasks: start_service.yml
  tags:
  - service